### ISSUE TITLE
Don't render the boilerplate in the license template.

### ISSUE THREAD

**Issue by lord63** [licenses/lice#44]
For example, the gpl-2.0 license, we don't have to render the [boilerplate](https://github.com/licenses/lice/blob/master/lice/template-gpl2.txt#L280) at the end of the license, all we need is just copy the content into a file named LICENSE.
Let me know if I was wrong.

**Comment by lord63** [comment]
My original meaning is don't render the variables(as I pointed in the url, in line 280)

> Copyright (C) {{ year }} {{ organization }}

just let them be.

the change was introduced in 09e327173ac9df8980618cec7b4c69b070fcc537

**Comment by lord63** [comment]
By the way, got this information from [here](http://choosealicense.com/licenses/gpl-2.0/)

> How to apply this license

> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file.

**Comment by ejmr** [comment]
> My original meaning is don't render the variables.

As in, don't create output like this?

> Copyright (C) 2015 John Doe

**Comment by lord63** [comment]
As far as I know, yeah, just let them be, don't render them.

**Comment by ejmr** [comment]
In my experience, I have always seen years and names explicitly included in the copyright line when using the GPL.  I will look for official documentation re. the GPL on that matter, but to give an example, when I started maintaining PHP Mode for Emacs I was told to update the copyright line(s) appropriately [like so](https://github.com/ejmr/php-mode/blob/master/php-mode.el).  So I don't think we should remove them from the template.  I *think* the GPL requires such information, but I could be wrong, so like I said I'll look for any documentation/information on the matter.
